server:
  port: 7777
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always